### ISSUE TITLE
How to use only the detection and ocr part of toolbox ?

### ISSUE THREAD

**Issue by calibretaliation** [kaylode/vietnamese-ocr-toolbox#6]
Hello, Im very appreciate your work and attempt to do something using it. However, I found that my work only requires parts of your pipeline, not all the steps.
So are there any methods or function that help me with this problem ?
Thank you very much đồng hương :D

**Comment by nhtlongcs** [comment]
We are glad that you are interested in our small project.
According to the issue title, you only need to execute two independent detection and ocr modules on the pipeline, right?

You can refer to the `run.py` source code [here](https://github.com/kaylode/vietnamese-ocr-toolbox/blob/master/run.py). It is simply a manual of our modules and a standalone executable. You can initialize as follows.

```python
det_model = Detection(
    config_path=det_config,
    weight_path=det_weight)
ocr_model = OCR(
    config_path=ocr_config,
    weight_path=ocr_weight)
```
Then you can execute them as follows:

```python
det_model(img,
        crop_region=True,
        return_result=False,
        output_path=crop_output_folder)
img_paths = list(glob(f'{crop_output_folder}/*')
texts = ocr_model.predict_folder(img_paths, return_probs=False)
```
With `crop_output_folder` is croped output detection folder path. 

The project has stopped for maintenance, but we still appreciate your interest. We are happy to answer your questions and your contributions to our work. 

Thanks, đồng hương xD

**Comment by whoisltd** [comment]
@nhtlongcs đối với detect ảnh chứng minh thư thì cần khoảng bao nhiêu ảnh để có thể detect được đầy đủ các vùng vậy b

**Comment by nhtlongcs** [comment]
> @nhtlongcs đối với detect ảnh chứng minh thư thì cần dùng khoảng bao nhiêu ảnh training để có thể detect được đầy đủ các vùng vậy b

@whoisltd Chúng mình không có dữ liệu eKYC đã gán nhãn mà chỉ thực hiện 1 vài experiment trên đó, positive cases mình đã update trong notebook. Mình không có dữ liệu chứng minh thư cũng như không training dữ liệu đó trong repo này.

**Comment by calibretaliation** [comment]
Hello again,
I am still working on a similar project as yours, and stucking at the stage of information correction and retrieval.
Can you please inform me some information of your correction steps ?
I have tons of questions about your correction module: Trie and TrieNode, can you provide me some sources to learn about these and their ideas of spelling correction ? 
Also, as I understand, are you checking the spelling base on your self-build dictionary, or a self-learning mechanics like nlp ?
 I am a learner so many thanks for you support, and of course I really really want to use your pre-built package, but Im a learner therefore I want to deal with this problem with your guides :D 
Thanks thanks thanks veryyyy muchhhh
