### ISSUE TITLE
Link model not found

### ISSUE THREAD

**Issue by thanhkhanhcntt** [kaylode/vietnamese-ocr-toolbox#7]

**Comment by cuong21951** [comment]
Bạn ơi update link model đi ạ

**Comment by nhtlongcs** [comment]
Chào bạn, 

Mình đã kiểm tra notebook inference và thấy mọi link vẫn đang hoạt động tốt, nếu bạn có vấn đề khi tải bạn có thể tự tải trực tiếp thông qua url-id tại `https://github.com/kaylode/vietnamese-ocr-toolbox/blob/master/tool/utils.py`. Hoặc có thể update pkg down `pip install gdown --upgrade` để tránh trường hợp không thể tải weight nhé 

<img width="727" alt="image" src="https://user-images.githubusercontent.com/45918109/174872083-4d858e8e-1d21-487b-80a8-1ed964abb05f.png">

**Comment by cuong21951** [comment]
Mình chạy từng part trong notebook của bạn thì 
![image](https://user-images.githubusercontent.com/63845367/174964589-7a555504-1640-4432-9bef-8cac052587c2.png)

**Comment by nhtlongcs** [comment]
Bạn update gdown bản mới nhất như mình đã mô tả nhé

**Comment by cuong21951** [comment]
![image](https://user-images.githubusercontent.com/63845367/174967008-3815313e-e59a-4095-be54-7bb84c53e864.png)
Mình upgrade gdown ở đây có đúng k nhỉ. Vẫn fail
