### ISSUE TITLE
Link dataset not found

### ISSUE THREAD

**Issue by HariWu1995** [kaylode/vietnamese-ocr-toolbox#8]
Can you please check the URL of both the datasets? I cannot access to that link.
![image](https://user-images.githubusercontent.com/22979330/182987194-a197265c-5d7e-4d9a-aa07-2c687facf574.png)

**Comment by HariWu1995** [comment]
I have found another URLs for your datasets on Kaggle:
- [MC-OCR](https://www.kaggle.com/datasets/domixi1989/vietnamese-receipts-mc-ocr-2021) 
- [SROIE](https://www.kaggle.com/datasets/urbikn/sroie-datasetv2)

**Comment by nhtlongcs** [comment]
Updated in ef8744b
